### ISSUE TITLE
[Arcs] Secure Timing

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/spotlight#138]
A few Vox cards

[Planet-Eater Loose](https://lederspotlight.netlify.app/card/ARCS-F1111) 
[Council Intrigue](https://lederspotlight.netlify.app/card/ARCS-CC12) 
[Armistice ](https://lederspotlight.netlify.app/card/ARCS-F216)

their When Secured effects refers to the agents on it. This implies the When Secured effect must be resolved before agents are returned/captured. This contradicts with base rule for Secure action which sequences them the other way. Which way is correct?

**Comment by jdyearsley** [comment]
I'm not sure this problem, if it is one, is solvable without extreme rewrites and issues. I would want a case where this looseness in order actually causes a problem before I targeted a solution. [Planet-Eater Loose](https://lederspotlight.netlify.app/card/ARCS-F1111) also, for example, is a case where the When Secured effect specifies a case where the card remains in the Court, while the base rule for Secure says to take the card.

Broadly, the When Secured action can modify the base Secure logic. _Technically,_ it makes the most sense to structure the Secure order as:
1. Resolve its When Secured action, if any.
2. Take the card (unless overridden).
3. Return/capture agents as necessary (unless overridden).
4. Refill the Court.

However, this really buries the lede on the Secure action and I would never want to write it this way in the core rules for the sake of a few cases in the campaign. Is there evidence of wide-scale confusion on this point, or is this confected?

**Comment by ledergamesmatt** [comment]
I don't believe there were any actual issues. This was just turmoilbyrd digging deep. But I would note that it's just kind of related to these attachment cards being looked at more closely (Armistice, etc)

I'll poke around a bit more and check in with turmoilbyrd

**Comment by ledergamesmatt** [comment]
from turmilbyrd:

> i think one confusion this question leads to is for [Dealmaker](https://cards.ledergames.com/card/ARCS-F103)  + [Diplomatic Fiasco](https://cards.ledergames.com/card/ARCS-CC13). Are agents returned before or after counting agents in supply for its When Secured effect

**Comment by jdyearsley** [comment]
That being said, I think it's fine to clarify the Diplomatic Fiasco order, since that could really affect things. Feel free to put in an FAQ.

**Comment by ledergamesmatt** [comment]
Added to faq240820 branch
