### ISSUE TITLE
[Feature] Alt text for card icons

### ISSUE THREAD

**Issue by jdyearsley** [LederCards/spotlight#66]
Is it possible to add alt text for screen readers, etc., to the game icons we use in card descriptions? For example, if someone uses a screen reader for the card Wrestlers in Oath, can we design the site so that the "defense die" icon reads "defense die" when it reaches the icon?

**Comment by seiyria** [comment]
this is done. it will infer from the icon name what to call it, so if the icons are named well it should be fine!
