### ISSUE TITLE
Clear search bar when you revisit page

### ISSUE THREAD

**Issue by jdyearsley** [LederCards/spotlight#76]
It looks like the site is still caching the earlier search even after I totally leave the page and go back. It should clear the search bar, though keeping the game is fine.

**Comment by seiyria** [comment]
Does it remember because of the query params in the URL bar? If you clear the text from there does it stop happening?

**Comment by tburrows13** [comment]
I go straight to https://cards.ledergames.com/ with no other params and it pre-populates with things (e.g. tag:"Admiral") without me doing anything else.
