### ISSUE TITLE
"Back" button doesn't always work

### ISSUE THREAD

**Issue by jdyearsley** [LederCards/spotlight#79]
A user submitted this bug, but I have also seen very strange "Back" button behavior where it sometimes takes multiple clicks (or swipes on mobile) to get back to the previous page I was on.

This is the behavior observed by the other user:
- Make a search (e.g. tag:"Caretaker")
- URL is now [https://cards.ledergames.com/search?q=tag:"Caretaker"&d=images&s=id&b=asc&p=0](https://cards.ledergames.com/search?q=tag:%22Caretaker%22&d=images&s=id&b=asc&p=0)
- Press "Back" in browser
- URL is now [https://cards.ledergames.com/search?q=tag:"Caretaker"](https://cards.ledergames.com/search?q=tag:%22Caretaker%22), page hasn't changed
- URL should now be whatever you were on when you search, e.g. "ADVANCED" page

**Comment by seiyria** [comment]
This was due to how I updated the URL when making searches. I'm not convinced it's entirely fixed, but let me know if this crops up again.
