### ISSUE TITLE
Make the ID searches look for IDs that contain the search term, not only exactly matching

### ISSUE THREAD

**Issue by jdyearsley** [LederCards/spotlight#82]
Right now, if I search "F2" or "F201" with Arcs selected, it doesn't bring up any cards, even though cards exist with the ID "ARCS/F201". Ideally, searching "F2" with Arcs selected would bring up all IDs that **contain** "F2" in Arcs rather than looking for exact matches, and "F201" should bring up "ARCS/F2O1".

I think it's fine to make all searches inclusive of results that contain the search, rather than looking for exact matches, since card ID searches will have numerals, and card titles basically never contain numerals, especially not a numeral directly adjacent to a letter. If an extra gate is needed, you might check the search for numerals, and if it does contain a number then the search looks for everything containing the search term.

**Comment by seiyria** [comment]
If you use `id:F2` it will do this - https://cards.ledergames.com/syntax#id - is your intention also to allow it on the bare text search (eg, `game:arcs f2`)?

**Comment by jdyearsley** [comment]
Ah, gotcha! The ID summary description says it looks for an exact match, but I see that it does work this way. Yes, it's more ideal for the bare text search to use this behavior too, since it covers more use cases with less effort, and there shouldn't be much downside because of the lack of numeral/letter combos outside IDs, as discussed above.

**Comment by seiyria** [comment]
I can add this to the bare text search. I probably changed the id search but never updated the description. I'll take a peek.
